version: '3'
services:
  readme-postgres:
    image: postgres:14
    container_name: readme-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - readme-postgres-data:/var/lib/postgresql/data
    networks:
      - readme-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  readme-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: readme-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - readme-network
    depends_on:
      readme-postgres:
        condition: service_healthy

volumes:
  readme-postgres-data:

networks:
  readme-network:
    driver: bridge
